### ISSUE TITLE
World for NPC

### ISSUE THREAD

**Issue by Technosword** [retrooper/packetevents#125]
Is there a way to get/set the world the NPC is spawning in or specify that? If not, I'd like you to add that method?

**Comment by retrooper** [comment]
Instead of letting you spawn an NPC in a world and dealing with it as if it were a normal player, we let you spawn an NPC for a player. Spawning it for a specific player will spawn it in their own world. If you want all players in a world to view it, you need to spawn it for all of them. We are sending packets to all of those clients. Have I misunderstood your question?

**Comment by Technosword** [comment]
Ah I understand, perhaps it would be better if you could get the world an NPC is spawned in so you can save it to a database and create a new Bukkit location with it later.

**Comment by retrooper** [comment]
I think that solution wouldn’t be too efficient, lets say a developer only wanted to spawn an NPC for an individual user. I don’t think an advanced NPC API is appropriate to be built into packetevents.

**Comment by retrooper** [comment]
Sorry for delayed response, I responded long ago, but the message didn’t send and I had no motivation to retype it.. 😆

**Comment by Technosword** [comment]
Makes sense, thank you!
