### ISSUE TITLE
ViaVersion support broken

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#274]
On the 2.0 branch, ViaVersion support broke today.  I can't join the 1.18.1 server from a 1.8 or a 1.18.2 client without a DecoderException.  This didn't occur yesterday.

**Comment by retrooper** [comment]
Is ViaVersion on the server?

**Comment by retrooper** [comment]
With Via and packetevents alone, it works.

**Comment by retrooper** [comment]
https://github.com/ViaVersion/ViaVersion/issues/2839

**Comment by retrooper** [comment]
We're currently in a sticky situation. ProtocolLib pushed their dev builds, we now only support those. But ViaVersion does not handle these dev builds properly. Well you will get some exceptions in your console due to Via. If you want to go back to a working version of packetevents, using older ProtocolLib with Via support, use https://github.com/retrooper/packetevents/commit/4d77af307c8c4ed36bd691ab5f2447a465823554

**Comment by retrooper** [comment]
Use https://jitpack.io/#retrooper/packetevents/2.0-4d77af307c-1 from jitpack.io

**Comment by retrooper** [comment]
Can you test the newest version with https://ci.viaversion.com/job/ViaVersion/lastBuild/ (Latest Via dev build) and https://ci.dmulloy2.net/job/ProtocolLib/ (Latest ProtocolLib dev build) and see if they work?

**Comment by MWHunter** [comment]
Broken for me still

**Comment by MWHunter** [comment]
seems to work now
