### ISSUE TITLE
FEATURE REQUEST - Allow plugins to decide if they should be in front of/behind ViaVer/PS

### ISSUE THREAD

**Issue by Jaren8r** [retrooper/packetevents#312]
As discussed on [Discord](https://discord.com/channels/811396969670901800/811396971059085364/961734249893998612), it was decided that PacketEvents would stay behind ViaVersion/ProtocolSupport on spigot because ProtocolSupport allows older versions to connect that PacketEvents doesn't support. While this might not matter for most plugins, it would be beneficial for anti cheat plugins to have that option to be in front of Via/PS, as Via/PS mess with a few things that become a headache to account for.

**Comment by MWHunter** [comment]
+1

I think it would be acceptable to break 1.4-1.6 client usage.  I don't see any point in using this old of clients.  Being in front of viaversion would make packetevents consistent for the proxy and server itself and would be powerful compared to ProtocolLib being unable to send cross-version packets like this.  The only downside is that it would increase the workload on the plugin developer for supporting multiple versions.  But that could be fixed with more abstraction with wrappers.

**Comment by retrooper** [comment]
Progress coming on this as soon as all critical bugs are fixed.

**Comment by retrooper** [comment]
Almost there i'd say.

**Comment by retrooper** [comment]
Anyway, my response was, if we decided to be ahead of ViaVersion, it would make sense to be ahead of ProtocolSupport.
But ProtocolSupport supports clients as old as 1.4.7 which we cannot handle. We also don't just prevent them from joining as that is just disabling half of ProtocolSupport's functionality and won't give us a good image. So we will just be behind them, hopefully it won't be a big issue. If you want to process based on client versions, make a proxy plugin. Right now we support velocity.
