### ISSUE TITLE
1.8 disconnect issue with WrapperPlayServerPlayerInfo 

### ISSUE THREAD

**Issue by MWHunter** [retrooper/packetevents#393]
I have gotten a report that with colored names, WrapperPlayServerPlayerInfo is encoded wrong on 1.8 and disconnects users

**Comment by NoJokeFNA** [comment]
We basically have to add support for modern versions in general:

https://wiki.vg/Protocol_History

#### 1.13-pre8
- Protocol version 390
- "Objective Value" in scoreboard objective and "Team Display Name" in teams are now text components, instead of raw strings.

https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerTeams.java#L161 (correct)
https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/wrapper/play/server/WrapperPlayServerScoreboardObjective.java#L72 (incorrect)

**Comment by MWHunter** [comment]
I did mean WrapperPlayServerPlayerInfo, updating the title

**Comment by MWHunter** [comment]
Maybe this was fixed by adventure changes?  This should be tested.
