### ISSUE TITLE
Inquiry Regarding Missing "Player Input" Packet (0x23)

### ISSUE THREAD

**Issue by RegotlyLong** [retrooper/packetevents#639]
I hope this message finds you well. I am reaching out regarding the absence of the "Player Input" packet (0x23) as specified in the https://wiki.vg/Protocol#Player_Input documentation.

While studying the protocol specifications, I noticed that the "Player Input" packet (0x23) is mentioned, but I have encountered challenges in locating this specific packet within the data packets.

Could you kindly provide clarification or guidance regarding the existence or implementation details of the "Player Input" packet (0x23)? I am eager to understand its usage and functionality in the context of the protocol.

Your assistance in addressing this inquiry would be greatly appreciated.

Thank you for your time and attention to this matter.

**Comment by retrooper** [comment]
I appreciate you reaching out. Since you closed this as completed I assume you have found the answer! In the past we committed to sticking to wiki.vg/Protocol naming to make it easier for beginners to study protocol specifications. Unfortunately wiki.vg/Protocol is indeed a wiki, allowing anyone to modify it and since that commitment many of the names have changed. This challenges us because we cannot simply break API conventions to make breaking changes. Fortunately many packets are similarly named or can be found by looking. I could explain how to really find the PacketEvents equivalent by diving into our source code or you could simply join our discord and ask whenever unsure. Thanks.
