### ISSUE TITLE
 Inquiry Regarding Removal of NMSPacket in Version 2.0

### ISSUE THREAD

**Issue by RegotlyLong** [retrooper/packetevents#640]
I hope this message finds you well. I am writing to inquire about the removal of NMSPacket in the recent Version 2.0.

I noticed that in the latest release, NMSPacket has been removed from the framework. Could you provide insight into the reasons behind its removal and whether there are plans to reintroduce or replace it in future updates?

Understanding the rationale behind this change and any potential alternatives or timelines for its restoration would be immensely helpful for our development efforts.

Your guidance or clarification on this matter would be greatly appreciated.

Thank you for your attention to this inquiry.

**Comment by retrooper** [comment]
I love the professionalism! I hope this response finds you well. NMSPacket was previously created as a handy reflection utility to process minecraft packets that have been decoded to Packet classes by the vanilla server. PacketEvents v1.8 relied solely on reflection to process packets. PacketEvents v2.0 has changed and now processes the network buffer before it is decoded. This means we no longer need reflection in order to process packets, and we can now use the Netty API, which minecraft also uses, to process these. One of the largest benefits of this change is the ease of maintenance. Over time lumps of reflection code becomes messy and cluttered.

If you still care about using the previously named "NMSPacket" for its reflection utilities to use elsewhere in your project, it is still present in 2.0 PacketEvents! It has been renamed to ReflectionObject and serves as a reflection utility rather than a packet wrapping utility.

**Comment by RegotlyLong** [comment]
Dear retrooper:
Haha, thanks for the reply: XD
I hope this message finds you well. I am writing to seek guidance on a couple of technical matters related to our system.

Usage of ReflectionObject:
I am currently exploring the utilization of ReflectionObject in Java but haven't fully grasped its application. Could you provide an example illustrating its usage? It would immensely help me understand its practical implementation better.

Issue with Player Receiving Skeepalive(S00):
I encountered an issue with player interaction after sending Skeepalive packets. Initially, players receive these packets without any problems. However, after a certain duration, they stop receiving them(C00). 
I'm curious about the possible reasons behind this unexpected behavior. 
Could you shed some light on the potential causes for such an occurrence?

I appreciate any assistance or insights you can provide on these matters. Thank you very much for your time and support.
Looking forward to your guidance.

**Comment by retrooper** [comment]
# Introduction
Dear @RegotlyLong :
I hope this message finds you well. I appreciate your desire to learn more about utilities inside our library.
Before we proceed, you never told me why you want to use our "ReflectionObject" utility. I explained that we no longer use it in packet-wrapping and it is simply a tool to make the usage of Java Reflection easier. To be more specific, finding fields inside of objects. 
Usage should be **straight forward** just by reading the source alone.
# How?
You start by wrapping the object you would like to read fields from.
Then you can call methods such as read, write, readByte(index), readInt(index), readDouble(index), writeDouble(index), ...etc
You can see that must specify the index so that we know which field of that specific type to read or write for you. 
For example, readInt(0) would read the value of the first integer in that object.
```java
ReflectionObject reflectionObject = new ReflectionObject(OBJECT_YOU_WANT_TO_READ_FROM);
//Read the value of the first integer
int value = reflectionObject.readInt(0);
//Write the value 100 to the first integer
reflectionObject.writeInt(0, 100);
```

# Your second issue

About your issue with Keep Alive packets, I don't see why this behavior seems to be happening on your server. Please provide us with some source to allow us to find the flaw in your code.

# Conclusion

Thank you for your interest in this project. If you do obtain an account on a platform called "Discord", please join our server to enable a much quicker communication method. Happy new year!

**Comment by RegotlyLong** [comment]
Happy new year!!
