### ISSUE TITLE
1.7.9 | inject early

### ISSUE THREAD

**Issue by WizzardHub** [retrooper/packetevents#69]
The issue is: check if a player is already online, cuz it someone joins with client version 1.8 and the same account on an other mc instance (in this case 1.9) loads the server list he will get his client version changed to 1.9.
voila.

**Comment by retrooper** [comment]
what? 😂 Sorry I didn’t understand a word you just said. How can two instances join the server at the same time. BTW have you tried putting ViaVersion on the spigot server? That might fix it.

**Comment by retrooper** [comment]
oh I think I get what you mean now.
If a user is on the server, and another minecraft instance but the same account on a different protocol version is on the server list, their clientversion gets overwritten?

**Comment by retrooper** [comment]
Join my discord server https://discord.gg/EkCYsjk
I can pass you a dev build or dev maven/gradle/whatever build through the server, that only fixes this bug and you can expect it to be fixed in the 1.8 release.
It is also easier to talk in the discord server, thanks for the report.
Should be easy to fix! 😃
