### ISSUE TITLE
Bstats error on startup on Velocity

### ISSUE THREAD

**Issue by KaspianDev** [retrooper/packetevents#888]
**Describe the bug**
PacketEvents errors on startup on velocity platform.

https://mclo.gs/rvAiXB9

**Software brand**
Velocity 3.3.0-SNAPSHOT (git-5154f029-b404)

**Plugins**
AntiPopup, (unknown)

**How To Reproduce**
Install my plugin AntiPopup
Launch it on Velocity
Notice the error

**Comment by booky10** [comment]
This is caused by your plugin shading multiple different packetevent platforms into the same jar
The spigot metric class overrides the velocity metrics class and therefore this error appears, this is not a packetevents issue

You either have to give users different jars, depending on platform, or relocate packetevents platform code to different packages (e.g. `io.github.retrooper.packetevents` -> `com.github.kaspiandev.antipopup.libs.packeteventsvelocity` for velocity and `io.github.retrooper.packetevents` -> `com.github.kaspiandev.antipopup.libs.packeteventsspigot` for spigot - then your universal jar has to shade the shaded jar of each of your platforms)
