### ISSUE TITLE
error with the latest dev build

### ISSUE THREAD

**Issue by Z3r0xh** [retrooper/packetevents#916]
**Describe the bug**
console spam

**Software brand**
NullcordX 3.8.8

**Plugins**
![image](https://github.com/user-attachments/assets/56712d96-23f7-4143-b934-65602cd16f8e)

**How To Reproduce**
Just place the latest dev build and wait for the users to enter

**Expected behavior**

**Screenshots**
Full server log (https://mclo.gs/e6bRQgD)

**Additional context**

NullcordX now accepts event packets, currently back to 2.4.1

**Comment by jonesdevelopment** [comment]
> I'm currently using 2.4.1

Try the latest dev build from Jenkins:
https://ci.codemc.io/job/retrooper/job/packetevents/lastSuccessfulBuild/

**Comment by Z3r0xh** [comment]
> > I'm currently using 2.4.1
> 
> Try the latest dev build from Jenkins: https://ci.codemc.io/job/retrooper/job/packetevents/lastSuccessfulBuild/

The one I mean that failed was that one. 2.5.0. I mean I had to downgrade to 2.4.1 again

**Comment by jonesdevelopment** [comment]
> The one I mean that failed was that one. 2.5.0. I mean I had to downgrade to 2.4.1 again

Oh, sorry, I misunderstood.

**Comment by Z3r0xh** [comment]
> > The one I mean that failed was that one. 2.5.0. I mean I had to downgrade to 2.4.1 again
> 
> Oh, sorry, I misunderstood.

Don't worry :D

**Comment by libraryaddict** [comment]
So the problem with IJukeboxSong is that a Component can actually be a raw string.
Except I'm not familiar enough with packetevents and the utilities to know how that implementation would look.

A brief look into nms internals seems like a component is written as a raw string if it's simple enough, otherwise it's written as json.
So packetevents could just handle this all as a string but then I don't know how to handle https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/protocol/item/jukebox/JukeboxSongs.java#L47

The actual implemention of jukebox was wrong, because I had naively believed that the vanilla jukebox songs were being sent as I had experienced with the other registries. Turns out you need a datapack installed or the code never fires
